### PR TITLE
Library modernisation

### PR DESCRIPTION
**Pull request by elitalon**
This implements all issues raised in the [library-modernisation](https://github.com/elitalon/quaderno-ios/milestones/library-modernisation) milestone, except for elitalon/quaderno-ios#6.

Note that the functionality of the framework is not complete yet. There is only support for ping and fetching the API rate limits, as it was before.

For Travis CI to work, an account on behalf of Quaderno should be ideally open. Also, once this has been merged to master, it is necessary to [push the specs](https://guides.cocoapods.org/making/making-a-cocoapod.html) for CocoaPods into [their repository](https://github.com/CocoaPods/Specs).

### CODE REVIEW

**Comment by polimorfico** [comment]
Thanks so much!! 🤗

**Comment by elitalon** [comment]
@polimorfico My pleasure! We would need to publish a 0.0.2 tag, similar to [the one I have in my fork](https://github.com/elitalon/quaderno-ios/releases/tag/0.0.2). Otherwise I cannot publish the framework in CocoaPods :crying_cat_face:

**Comment by polimorfico** [comment]
Done!! ;)

**Comment by elitalon** [comment]
Aaaaand [we're live](https://github.com/CocoaPods/Specs/tree/master/Specs/Quaderno), with [docs included](http://cocoadocs.org/docsets/Quaderno) :bowtie:

**Comment by polimorfico** [comment]
Awww yeah!! 😎

**Pull request merged**
